"""adiciona customer, server, agent, metric e alert

Revision ID: a1e9958a8cb3
Revises: f3dda77a06dd
Create Date: 2026-08-03 21:13:22.677904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e9958a8cb3'
down_revision: Union[str, Sequence[str], None] = 'f3dda77a06dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_customer_user_name')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=False)
    op.create_table('servers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('server_type', sa.Enum('VPS', 'DEDICATED', 'CLOUD', 'DATABASE', 'DOCKER', 'VM', 'OTHER', name='server_type'), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'name', name='uq_server_customer_name')
    )
    op.create_index(op.f('ix_servers_customer_id'), 'servers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_servers_hostname'), 'servers', ['hostname'], unique=False)
    op.create_index(op.f('ix_servers_ip_address'), 'servers', ['ip_address'], unique=False)
    op.create_table('agents',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('OFFLINE', 'ONLINE', 'DISABLED', name='agent_status'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_update', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_agents_server_id'), 'agents', ['server_id'], unique=True)
    op.create_table('alerts',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_server_status', 'alerts', ['server_id', 'status'], unique=False)
    op.create_table('metrics',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('disk_usage', sa.Float(), nullable=False),
    sa.Column('network_in_bytes', sa.BigInteger(), nullable=False),
    sa.Column('network_out_bytes', sa.BigInteger(), nullable=False),
    sa.Column('process_count', sa.Integer(), nullable=False),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cpu_usage >= 0 AND cpu_usage <= 100', name='ck_metrics_cpu_range'),
    sa.CheckConstraint('disk_usage >= 0 AND disk_usage <= 100', name='ck_metrics_disk_range'),
    sa.CheckConstraint('memory_usage >= 0 AND memory_usage <= 100', name='ck_metrics_memory_range'),
    sa.CheckConstraint('response_time_ms IS NULL OR response_time_ms >= 0', name='ck_metrics_response_time_positive'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_server_created_at', 'metrics', ['server_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_server_created_at', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('ix_alerts_server_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_agents_server_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_servers_ip_address'), table_name='servers')
    op.drop_index(op.f('ix_servers_hostname'), table_name='servers')
    op.drop_index(op.f('ix_servers_customer_id'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
